[package]
name = "tntt"
version = "0.4.1"
entrypoint = "src/lib.typ"
authors = ["chillcicada"]
license = "MIT"
description = "Tntt is Not an official Typst Thesis Template for Tsinghua university (THU)..."
repository = "https://github.com/chillcicada/tntt"
keywords = ["Tsinghua University", "thesis", "template", "THU"]
categories = ["thesis"]
exclude = [".*", "test"]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
